### ISSUE TITLE
pixels drawing issue for mouse dataset

### ISSUE THREAD

**Issue by theodev** [SpatialMetabolomics/webserver#4] opened 2015-05-29 16:18 UTC
![test_server_on_spark](https://cloud.githubusercontent.com/assets/3242749/7887115/f94a3624-062e-11e5-9c70-1fcbdfde4ab3.png)

not reproduced for other dataset

**Comment by andy-d-palmer** [comment] 2015-05-29 16:40
These datasets look fine on sergey's server. It's a problem at the AWS end.

**Comment by DarthPumpkin** [comment] 2015-06-02 08:48
The issue is caused by wrong pixel sizes. The ion images are embedded into the HTML page as vector graphics where each pixel is a rectangle that has a width and height assigned to it. When comparing the HTML pages returned from both the AWS server and Sergey's server, the pixel sizes differ. Sergey's pixel sizes are 2x2, the AWS ones are 55x55. This means the AWS images actually contain the correct pixels, they are just too large.

**Comment by DarthPumpkin** [comment] 2015-06-02 13:57
Fixed with commit 8bb3695954a4b3fede40170e498e66b29bb5d6b5.

**Closed by DarthPumpkin** 2015-06-02 13:57 UTC
Labels: bug
